### ISSUE TITLE
No indication that "make markers real" has finished

### ISSUE THREAD

**Issue by bbryson** [sillsdev/solid#13]
When I use the command Make Markers Real, it can take a bit of time to complete, but there is no indication that it has finished, and the floppy disk icon doesn't turn blue to indicate that there are unsaved changes.  I expect the icon to turn blue once the process has completed.  (This is similar to Notepad++ when I change a file from Windows to Unix line endings:  It sits there doing nothing for a while, and the floppy icon stays gray.  But as soon as it turns blue, then I know that it has completed and now is the time to save it.)

Steps to reproduce:
1. Open the attached file in Solid (you should be able to double click the .solid file, or do File/Open Lexicon from within Solid).
2. Notice that the ps markers are blue and have a + sign:  \+ps     This means they are not real; they are only inferred.  If I were to save the file right now, there would be no \ps markers in it.  That is expected.  (When I click Save, it is saving both the settings .solid file, and the SFM file.)
3. Use menu item Fix/Quick Fixes and then choose the tab "Make Markers Real".  In the box at the top, change the contents to only have ps in it.  Then click the blue link that says "I know what I'm doing and have backed up".
4. Wait for some amount of time (15 seconds? 30 seconds?).    
5. Exit Solid.  Then reopen the file.  Notice the ps markers are blue again with the plus--it did not save the file.  (And if you open the SFM file in Notepad++ you will find there are no \ps markers in it.)
6. Repeat steps 3 & 4.  Click Refresh.  Notice the ps markers are now black, but the floppy icon is still gray.  Exit Solid without saving.  Reopen the file.  Notice the ps markers are blue with plus again--it did not save.  (And if you open the SFM file in Notepad++ you will find there are no \ps markers in it.)
7. Repeat steps 3&4.  Choose menu option "File".  Notice the "Save" option is grayed out.  There is no way for me to save the file at this point.
8. Make a trivial edit in the record in the right pane (for instance, delete a letter and then retype it).  Now the icon is blue and the File/Save command is active.  Use one of those to save the file.  Exit Solid, reopen, and notice that now the \ps markers are black.  In Notepad++ there are now \ps markers in the file.
9. Desired behavior:  After Solid has finished editing the file, the icon should be blue and the File/Save command should be available, even without clicking Recheck.  I should be able to save the file without making an edit first.

**Comment by bbryson** [comment]
![image](https://github.com/sillsdev/solid/assets/4039852/6b462ae0-dd8b-425d-adc1-da669f1541f2)

**Comment by megahirt** [comment]
Summary: there is no user feedback that the change process has started or finished.

- Beth is suggesting that the Save icon should illuminate as blue indicating that changes were made that are unsaved (and clicking the Save button with save them).
- Another option is to ensure the process is synchronous and provide a progress bar.  The save button should also illuminate if there are unsaved changes.

**Comment by bbryson** [comment]
Now when it finishes:
 - There is a message saying how many changes were made--really helpful!  I do usually wonder how many.
 -  The inferred markers turn black.
 -  The File/Save option is available.
 - The floppy icon turns blue.
Wonderful!!  This will really help a lot!!
