### ISSUE TITLE
Can't resize marker list pane

### ISSUE THREAD

**Issue by bbryson** [sillsdev/solid#16]
When I edit the settings for a marker, the dialog box has a pane with a list of all the markers.  But it is quite narrow, and there is no way to make it wider.  Most markers only need that much space, but sometimes some need more.

It would be nice to be able to resize that pane.  Absent that, if there could at least be a tooltip when we hover over a marker, even that would help.

Attaching a video to show the steps, and what does and doesn't work for seeing the full marker.

https://github.com/sillsdev/solid/assets/4039852/990284d0-6069-4182-a8d3-b42024881c11

![image](https://github.com/sillsdev/solid/assets/4039852/65901cec-0b75-43fc-aacc-8ffea98bb158)

**Comment by bbryson** [comment]
Attaching the project and .solid file from the video.  Remove .txt from both filenames.
[AruStems-LongMarkers.sfm.txt](https://github.com/user-attachments/files/15880373/AruStems-LongMarkers.sfm.txt)
[AruStems-LongMarkers.solid.txt](https://github.com/user-attachments/files/15880374/AruStems-LongMarkers.solid.txt)

**Comment by bbryson** [comment]
This looks really good!  Hooray!  I can now resize the pane, and the other parts kept their behavior also.

There is one tiny fiddly that I didn't mention.  At the top of the dialog it is supposed to say the marker "can occur..."   This appears for short markers, but it got truncated for the long ones (I'll attach screenshots).  This is really minor, and I didn't mention it before.  We can live with this, but I wanted to at least note it.
![LongMarkerCan2](https://github.com/sillsdev/solid/assets/4039852/84cf6b81-a606-4300-aa04-19ddb262642b)
![LongMarker-Can1](https://github.com/sillsdev/solid/assets/4039852/0a68988d-8a1f-4d30-a3c8-e6d36bf21639)
![ShortMarker-CanOccur](https://github.com/sillsdev/solid/assets/4039852/f0891c68-b12f-461a-9978-4a70b1f2f207)

**Comment by megahirt** [comment]
Thanks @bbryson for the feedback!  I've created a new issue #25 so let's discuss further over there.
