### ISSUE TITLE
.Net version issue

### ISSUE THREAD

**Issue by meishala** [sillsdev/solid#3]
![solid_dotnet](https://user-images.githubusercontent.com/36694235/36471958-41300120-172b-11e8-924b-edb273c54637.JPG)

I have tried to install Solid 0.20.1 but it tells me that I need .Net 4.6.1 or greater. I checked my .Net version in the registry and I have 4.7.x (see image). 

Please advise.

**Comment by andrew-polk** [comment]
@meishala,

Sorry about that. We have corrected the issue in the latest version.
Please grab Solid 0.21.3 or later from https://software.sil.org/solid/download/.

Andrew Polk
Language Software Developer
SIL International
