### ISSUE TITLE
Upgrade to .NET4.8.1

### ISSUE THREAD

**Issue by ethnos-men** [sillsdev/solid#31]
Hello,

- I have short question regarding an upgrade to .NET4.8.1.
- Are you aware of any users still using Windows Vista? I guess that is not the case. But I just wanted to make sure.
- Because .NET4.8.1 is not supported by Windows Vista.

Greetings,
Markus

**Comment by megahirt** [comment]
I do not want to support Windows Vista for new versions of Solid.  We released v1.0.1 this summer with .Net 4.6.1 so that one will continue to support Vista.  I'm happy to upgrade and leave Vista behind!  Thanks @ethnos-men

**Comment by josephmyers** [comment]
#34 was merged
